name: Generate Ivan-FluX JSON

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘন্টায়
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pycryptodome

      - name: Run Generator
        env:
          AES_SECRET: ${{ secrets.AES_SECRET }}
          LIVXOW_URL: ${{ secrets.LIVXOW_URL }}
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Ivan-FluX.json
          git commit -m "Update Ivan-FluX.json" || exit 0
          git push
